version: '2.4'

services:

  eventstore:
    image: eventstore/eventstore:release-4.1.3
    container_name: "cqrs4j-quarkus-example-eventstore"
    ports:
      - "1113:1113"
      - "2113:2113"
    networks:
      - cqrs4j-quarkus-example-net
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2113/stats || exit 1"]
      interval: 5s
      timeout: 2s

  jkmq-postgres:
    image: postgres:11.0
    container_name: "cqrs4j-quarkus-example-postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=querydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc
    networks:
      - cqrs4j-quarkus-example-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  cqrs4j-quarkus-example-net:
    name: cqrs4j-quarkus-example-net
  